// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef copo_h
#define copo_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>

class ControleJanelaCopo {
public:
  ControleJanelaCopo();
  Fl_Double_Window *winCopo;
  Fl_Box *copo1;
  Fl_Box *copo2;
  Fl_Button *zerarcopo;
private:
  void cb_zerarcopo_i(Fl_Button*, void*);
  static void cb_zerarcopo(Fl_Button*, void*);
public:
  Fl_Box *copo3;
  Fl_Box *copo4;
  Fl_Box *copo5;
  Fl_Box *gelo;
  void mostrarjanela1();
  void fecharJanela();
  void abrirJanela();
  ~ControleJanelaCopo();
  void mostrarjanela2();
  void cbEsvaziar();
  void mostrarjanela3();
  void mostrarjanela4();
  void mostrarjanela5();
  void gelo1();
  void gelo2();
  void mostrargelo();
};
#endif
