// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "painel.h"

void ControleJanela::cb_agua_i(Fl_Repeat_Button*, void*) {
  this->botaoAgua();
}
void ControleJanela::cb_agua(Fl_Repeat_Button* o, void* v) {
  ((ControleJanela*)(o->parent()->user_data()))->cb_agua_i(o,v);
}

ControleJanela::ControleJanela() {
  { Painel = new Fl_Double_Window(398, 387);
    Painel->color(FL_BACKGROUND2_COLOR);
    Painel->user_data((void*)(this));
    { agua = new Fl_Repeat_Button(130, 240, 145, 55, "AGUA");
      agua->box(FL_GTK_ROUND_DOWN_BOX);
      agua->color((Fl_Color)6);
      agua->callback((Fl_Callback*)cb_agua);
      agua->when(FL_WHEN_ENTER_KEY);
    } // Fl_Repeat_Button* agua
    { gelo = new Fl_Repeat_Button(130, 305, 145, 55, "GELO");
      gelo->box(FL_GTK_ROUND_DOWN_BOX);
      gelo->color((Fl_Color)6);
    } // Fl_Repeat_Button* gelo
    { mensagem = new Fl_Output(80, 175, 250, 55);
    } // Fl_Output* mensagem
    { temp = new Fl_Value_Output(165, 30, 105, 45, "TEMPERATURA ATUAL");
      temp->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Value_Output* temp
    { NivelAgua = new Fl_Progress(100, 105, 220, 45);
      NivelAgua->selection_color((Fl_Color)177);
    } // Fl_Progress* NivelAgua
    Painel->end();
  } // Fl_Double_Window* Painel
}
